#157356491 ft add coveralls badge
andela/wg-bigas-opus pull request #20
Opened 2018-05-16 05:10 UTC by mutoromike

**What does this PR do?**

Adds a Coveralls badge and provides builds information from Travis CI. 

**Build Information**
<img width="991" alt="screen shot 2018-05-16 at 07 47 03" src="https://user-images.githubusercontent.com/26790578/40097768-a7dae63c-58e0-11e8-89d1-548f145c8e3f.png">

**Added badge**
<img width="191" alt="screen shot 2018-05-16 at 07 53 53" src="https://user-images.githubusercontent.com/26790578/40097782-c2237b44-58e0-11e8-9550-6edabbdd2948.png">

**What are the relevant pivotal tracker stories?**

Add coveralls badge to the repo.
ID: #157356491

2018-05-16 07:52 UTC, Kalela approved these changes
Great job

2018-05-16 08:34 UTC, meshnesh approved these changes
good work

2018-05-16 09:39 UTC, lakivisi-zz requested changes
put coveralls beside the travis badge horizontally

2018-05-16 09:41 UTC, lakivisi-zz requested changes
put coveralls beside the Travis badge horizontally

Is it integrated to all builds on GitHub,

2018-05-16 09:47 UTC, betsybeth commented on .travis.yml
> +after_success:
LGTM

2018-05-17 09:10 UTC, FelixWambiri approved these changes
Good Implementation.

2018-05-17 10:07 UTC, mutoromike commented
ReStructured Text formatting does not allow me to do that.
New format:
<img width="753" alt="screen shot 2018-05-17 at 13 03 20" src="https://user-images.githubusercontent.com/26790578/40171181-2a902f86-59d3-11e8-940f-6edf42ad461b.png">

2018-05-17 10:07 UTC, mutoromike commented
All builds will be picked up once merged to develop.

2018-05-17 11:37 UTC, betsybeth approved these changes
LGTM

2018-05-17 11:39 UTC, frankip approved these changes
👍 
LGTM

2018-05-17 11:47 UTC, mutoromike commented
<img width="218" alt="screen shot 2018-05-17 at 14 45 09" src="https://user-images.githubusercontent.com/26790578/40175563-29d45d20-59e1-11e8-9851-656313c7aa9f.png">

2018-05-17 13:07 UTC, lakivisi-zz approved these changes

2018-05-17 14:44 UTC, merged