#157110843 add fitbit support
andela/wg-bigas-opus pull request #21
Opened 2018-05-16 05:33 UTC by mutoromike

**What does this PR do?**

Allows a user to integrate Wger to work with Fitbit, which is a more advanced application that combines all nutritional factors such as workouts and exercises, nutrition etc. By adding Fitbit support, a user is able to see information while not having to log in to Fitbit every single time.

**Sync from Fitbit button that allows a onetime authentication**
<img width="397" alt="screen shot 2018-05-16 at 08 31 03" src="https://user-images.githubusercontent.com/26790578/40098313-8fbe188c-58e3-11e8-8f77-7d31cbeffce8.png">

**What are related PT stories?**
Add Fitbit support. 
ID: #157110843

2018-05-16 08:36 UTC, meshnesh requested changes
request for reviewers for the PR and fix the conflicting files

2018-05-16 09:28 UTC, FelixWambiri commented on wger/core/views/fitbit.py
> +            raise Exception("Action unsuccessful")
Nice Implementation especially good work on the comments.It makes it easy to go through and understand.

2018-05-16 09:29 UTC, FelixWambiri approved these changes
LGTM

2018-05-16 09:44 UTC, lakivisi-zz requested changes
Upload screenshot of the whole view with the button

2018-05-17 08:31 UTC, Kalela commented on .travis.yml
> +  - coverage run --source='.' ./manage.py test
Good work keeping track of your old task throughout the development period

2018-05-17 08:31 UTC, Kalela approved these changes
LGTM

2018-05-17 09:14 UTC, frankip approved these changes
LGTM

2018-05-17 09:14 UTC, frankip commented on wger/core/views/misc.py
> +def fitbitLogin(request):
👍

2018-05-17 09:22 UTC, mutoromike commented
After syncing with Fitbit, the data is presented as shown below:
<img width="403" alt="screen shot 2018-05-17 at 12 13 47" src="https://user-images.githubusercontent.com/26790578/40168741-e89c473c-59cc-11e8-885c-4792713c47c3.png">

2018-05-17 11:38 UTC, betsybeth approved these changes
LGTM

2018-05-17 11:41 UTC, meshnesh approved these changes

2018-05-17 14:10 UTC, lakivisi-zz approved these changes

2018-05-17 14:10 UTC, merged