Disable logged in users from accessing the login page
andela/wg-bigas-opus pull request #35
Opened 2018-05-30 09:41 UTC by FelixWambiri

**Description of Task to be completed?**
* Disable logged in Users from accessing the login page

**How should this be manually tested?**
* Login with any account
* Click on the back button

**What are the relevant pivotal tracker stories?**
* #157840079

**Background context**
* At the moment when a logged in user clicks on the back button they can access the login page.

2018-05-30 15:34 UTC, mutoromike approved these changes

2018-05-30 16:49 UTC, meshnesh approved these changes
Nice implementation and completing the task

2018-05-30 19:15 UTC, betsybeth approved these changes
Good work.LGTM

2018-05-31 07:49 UTC, Kalela approved these changes
LGTM

2018-05-31 08:17 UTC, frankip requested changes
Dont push the settings file
add the settings to gitignore

2018-05-31 08:17 UTC, frankip commented on wger/core/views/user.py
> +    try:
good job 
work fine

2018-05-31 08:24 UTC, FelixWambiri commented on wger/core/views/user.py
> +    try:
Thanks,I have deleted the settings file

2018-05-31 09:00 UTC, merged